### ISSUE TITLE
fitGAM error in quantile.default

### ISSUE THREAD

**Issue by zoesteier** [statOmics/tradeSeq#11]
When trying to run fitGAM on raw count data (a filtered matrix of 5 highly expressed genes x ~35,000 cells), I get the following error:

> gamList <- fitGAM(counts = counts, pseudotime = slingPseudotime(crv, na = FALSE), cellWeights = slingCurveWeights(crv))

> Error in quantile.default(x, p = p) : missing values and NaN's not allowed if 'na.rm' is FALSE

Do you have any idea what could be causing this error? I already confirmed that there are no NAs in counts, pseudotime, or cellWeights, and there are no genes with all zero counts on this filtered list.

**Comment by HectorRDB** [comment]
Hi,
I suspect that the error comes from only using 5 genes, and that for some cells, all those genes are zero. By default, tradeSeq uses [edgeR's calcNormFactors](https://www.rdocumentation.org/packages/edgeR/versions/3.14.0/topics/calcNormFactors) function to normalize for sequencing depth.
Can you try running `any(colSums(counts) == 0)`?
If this does not return TRUE, the error is somewhere else. Then, please let me know what the [traceback](https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/traceback) is.
Thanks

**Comment by zoesteier** [comment]
Thanks Hector! You are correct - there were some cells that had all zero counts for this small set of genes. When running on a larger set of genes (and making sure that any(colSums(counts) == 0) is FALSE), fitGAM runs without error, but I now run into the following error when trying to plot the knots:

Error in slingCurves(curve)[[ii]]$s[p, seq_len(2)] : 
  subscript out of bounds

2. rbind(knots_dim, slingCurves(curve)[[ii]]$s[p, seq_len(2)])
1. plotGeneCount(rd = sling_dim_reduce, curve = crv, counts = counts, gene = "Trbc1", models = gamList)

Do you know what could be causing this? Thanks for your help!

**Comment by zoesteier** [comment]
Hi Hector,

I think I found a possible cause for this error. When I ran slingshot, I used approx_points = 200 to speed up getCurves() (https://github.com/kstreet13/slingshot/issues/31). This results in slingCurves(crv)[[1]]$s having 200 rows rather than one row per cell, which causes the "subscript out of bounds" error when trying to plot knots.

Is it possible in tradeSeq to find the approximate location of the knots using the results of slingshot's approx_points?

Thanks!

**Comment by HectorRDB** [comment]
This should fix it

**Comment by zoesteier** [comment]
Hi Hector,
Sorry, this did not fix the issue. length(slingCurves(crv)[[ii]]$lambda) is the same length as the number of cells (which is different from dim(slingCurves(curve)[[ii]]$s)[1]), so I get the same error as before. I tried looking in the crv object to find either the pseudotime corresponding to the approx_points or the 2D dimensions of each cell projected onto the principal curve, but didn't find either. My goal is to find which knots to use for the earlyDETest by plotting the approximate locations of the knots.
