### ISSUE TITLE
Getting error when running fitGAM and evaluateK

### ISSUE THREAD

**Issue by balthasar0810** [statOmics/tradeSeq#115]
Hi everybody,

running fitGAM and evaluateK, I am always getting the same error:
Error in gam.fit4(x, y, sp, Eb, UrS = UrS, weights = weights, start = start,  : 
  inner loop 3; can't correct step size

My code for fitGAM is:
set.seed(7)
pseudotime <- slingPseudotime(seuObj.slingshot, na = FALSE)
cellWeights <- slingCurveWeights(seuObj.slingshot)
sce <- fitGAM(counts = as.matrix(seuObj@assays$RNA@counts[genes.tmp,cells.tmp]), pseudotime = pseudotime, cellWeights = cellWeights, nknots = 6, verbose = T)

What am I doinh wrong here?

Thanks, Chris

**Comment by balthasar0810** [comment]
Just to add: evaluateK starts working and throws this error at 21%.
|+++++++++++                                       | 21% ~41m 03s     

Chris

**Comment by koenvandenberge** [comment]
Hi Chris,

This is an error a few other users have reported and should be fixed in the most recent versions of `tradeSeq`. Could you please try re-installing from our Github page and trying again?

Thanks,
Koen

**Comment by balthasar0810** [comment]
Thanks so much for the quick reply. I will do and give you feedback. Chris

**Comment by balthasar0810** [comment]
It works now. Still getting warnings:
In max(abs(logR)) : no non-missing arguments to max; returning -Inf

Don't know what this means. Unfortunately, evaluateK does not show the expected plots (no plots at all). I pointed this out in another issue. 

Thanks, Chris

**Comment by koenvandenberge** [comment]
Hi @balthasar0810 

Thank you for getting back to us. Could you provide us with a reproducible example (e.g. using a subset of your data) so that we could look into it?

**Comment by koenvandenberge** [comment]
Closing due to inactivity, feel free to reopen if the issue is not resolved.
