### ISSUE TITLE
fitGAM: Error in Biobase::exprs(cds) : object 'cds' not found

### ISSUE THREAD

**Issue by BrianLohman** [statOmics/tradeSeq#44]
Hello,

I started with the same issue as #32, but after correcting the sparse matrix problem I get another error:

```Error in Biobase::exprs(cds) : object 'cds' not found```

I am working with the devel install of tradeSeq via GitHub, installed today. 

```
# make Seurat object
path <- Read10X(data.dir = "./16249X1/outs/filtered_feature_bc_matrix/")
donor1 <- CreateSeuratObject(counts = path, project = "16249X1", min.cells = 0, min.features = 0)

# read in list of cell barcodes of interest and subset
keep1 = read.csv("16249X1/outs/analysis/clustering/graphclust/clusters.csv")
keep1 = keep1[keep1$Cluster == "2", "Barcode"]
keep1 = gsub("-1", "", keep1, perl = FALSE)
donor1_fibroblast = subset(donor1, cells = keep1)

# convert to Monocle format and generate pseudotime
data <- as.matrix(donor1_fibroblast@assays$RNA@data) # no sparse matrix
pd <- new('AnnotatedDataFrame', data = donor1_fibroblast@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)
donor1_fibroblast_cds <- newCellDataSet(data, phenoData = pd,  featureData = fd,
          expressionFamily = negbinomial.size())

donor1_fibroblast_cds <- estimateSizeFactors(donor1_fibroblast_cds)
donor1_fibroblast_cds <- reduceDimension(donor1_fibroblast_cds, max_components = 2)
donor1_fibroblast_cds <- orderCells(donor1_fibroblast_cds)

# run tradeSeq
library(tradeSeq)
donor1_fibroblast_sce <- fitGAM(donor1_fibroblast_cds, verbose = TRUE)
Error in Biobase::exprs(cds) : object 'cds' not found
```
```donor1_fibroblast_cds``` is a valid CellDataSet object and I can generate the plot of pseudotime with Monocle. 

Any help would be much appreciated. 

Cheers,

Brian

**Comment by HectorRDB** [comment]
Hi @BrianLohman,
Thanks for you interest in tradeSeq.
I think the latest push (Version 1.3.01) should fix it. Let me know if it doesn't
Thanks

**Comment by BrianLohman** [comment]
Hi @HectorRDB,

Thanks so much for your prompt reply. I pulled 1.3.01 from GitHub but the issue still persists. I've added some additional session info below.

Thank you for your help,

Brian


```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
 [1] splines   stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Seurat_3.1.4        monocle_2.14.0      DDRTree_0.1.5       irlba_2.3.3         VGAM_1.1-2         
 [6] ggplot2_3.3.0       Matrix_1.2-18       dplyr_0.8.5         devtools_2.3.0      usethis_1.6.1      
[11] tradeSeq_1.3.01     Biobase_2.46.0      BiocGenerics_0.32.0

loaded via a namespace (and not attached):
  [1] reticulate_1.14             tidyselect_1.0.0            htmlwidgets_1.5.1           RSQLite_2.2.0              
  [5] AnnotationDbi_1.48.0        grid_3.6.3                  combinat_0.0-8              docopt_0.6.1               
  [9] BiocParallel_1.20.1         Rtsne_0.15                  RNeXML_2.4.3                munsell_0.5.0              
 [13] mutoss_0.1-12               codetools_0.2-16            ica_1.0-2                   future_1.16.0              
 [17] withr_2.1.2                 colorspace_1.4-1            fastICA_1.2-2               knitr_1.28                 
 [21] uuid_0.1-4                  zinbwave_1.8.0              rstudioapi_0.11             SingleCellExperiment_1.8.0 
 [25] ROCR_1.0-7                  gbRd_0.4-11                 listenv_0.8.0               NMF_0.22.0                 
 [29] Rdpack_0.11-1               slam_0.1-47                 GenomeInfoDbData_1.2.2      mnormt_1.5-6               
 [33] bit64_0.9-7                 pheatmap_1.0.12             rhdf5_2.30.1                rprojroot_1.3-2            
 [37] TH.data_1.0-10              vctrs_0.2.4                 xfun_0.12                   R6_2.4.1                   
 [41] doParallel_1.0.15           GenomeInfoDb_1.22.1         rsvd_1.0.3                  locfit_1.5-9.4             
 [45] bitops_1.0-6                DelayedArray_0.12.3         assertthat_0.2.1            scales_1.1.0               
 [49] multcomp_1.4-12             gtable_0.3.0                phylobase_0.8.10            npsurv_0.4-0               
 [53] globals_0.12.5              processx_3.4.2              sandwich_2.5-1              rlang_0.4.5                
 [57] genefilter_1.68.0           lazyeval_0.2.2              princurve_2.1.4             reshape2_1.4.3             
 [61] backports_1.1.5             tools_3.6.3                 gridBase_0.4-7              ellipsis_0.3.0             
 [65] gplots_3.0.3                RColorBrewer_1.1-2          sessioninfo_1.1.1           ggridges_0.5.2             
 [69] TFisher_0.2.0               Rcpp_1.0.3                  plyr_1.8.6                  progress_1.2.2             
 [73] zlibbioc_1.32.0             purrr_0.3.3                 RCurl_1.98-1.1              densityClust_0.3           
 [77] ps_1.3.2                    prettyunits_1.1.1           pbapply_1.4-2               viridis_0.5.1              
 [81] cowplot_1.0.0               zoo_1.8-7                   S4Vectors_0.24.4            SummarizedExperiment_1.16.1
 [85] ggrepel_0.8.2               cluster_2.1.0               fs_1.3.2                    magrittr_1.5               
 [89] data.table_1.12.8           RSpectra_0.16-0             lmtest_0.9-37               RANN_2.6.1                 
 [93] mvtnorm_1.1-0               fitdistrplus_1.0-14         matrixStats_0.56.0          pkgload_1.0.2              
 [97] patchwork_1.0.0             hms_0.5.3                   lsei_1.2-0                  xtable_1.8-4               
[101] XML_3.99-0.3                sparsesvd_0.2               IRanges_2.20.2              gridExtra_2.3              
[105] HSMMSingleCell_1.6.0        testthat_2.3.2              compiler_3.6.3              tibble_2.1.3               
[109] KernSmooth_2.23-16          crayon_1.3.4                htmltools_0.4.0             mgcv_1.8-31                
[113] tidyr_1.0.2                 howmany_0.3-1               DBI_1.1.0                   slingshot_1.4.0            
[117] rappdirs_0.3.1              MASS_7.3-51.5               ade4_1.7-15                 cli_2.0.2                  
[121] gdata_2.18.0                metap_1.3                   igraph_1.2.4.2              GenomicRanges_1.38.0       
[125] pkgconfig_2.0.3             sn_1.5-5                    rncl_0.8.4                  registry_0.5-1             
[129] numDeriv_2016.8-1.1         locfdr_1.1-8                plotly_4.9.2                xml2_1.2.5                 
[133] foreach_1.5.0               annotate_1.64.0             rngtools_1.5                multtest_2.42.0            
[137] pkgmaker_0.31.1             XVector_0.26.0              bibtex_0.4.2.2              stringr_1.4.0              
[141] callr_3.4.3                 digest_0.6.25               tsne_0.1-3                  sctransform_0.2.1          
[145] RcppAnnoy_0.0.16            softImpute_1.4              leiden_0.3.3                uwot_0.1.8                 
[149] edgeR_3.28.1                curl_4.3                    kernlab_0.9-29              gtools_3.8.1               
[153] jsonlite_1.6.1              lifecycle_0.2.0             nlme_3.1-144                clusterExperiment_2.6.1    
[157] Rhdf5lib_1.8.0              desc_1.2.0                  viridisLite_0.3.0           limma_3.42.2               
[161] fansi_0.4.1                 pillar_1.4.3                lattice_0.20-38             plotrix_3.7-7              
[165] httr_1.4.1                  pkgbuild_1.0.6              survival_3.1-8              glue_1.3.1                 
[169] remotes_2.1.1               qlcMatrix_0.9.7             FNN_1.1.3                   png_0.1-7                  
[173] iterators_1.0.12            bit_1.1-15.2                stringi_1.4.6               HDF5Array_1.14.4           
[177] blob_1.2.1                  caTools_1.18.0              memoise_1.1.0               future.apply_1.4.0         
[181] ape_5.3        
```

**Comment by HectorRDB** [comment]
Thanks for that info @BrianLohman 
Do you still get the same error? Or do you get a different error?

**Comment by BrianLohman** [comment]
Sorry, @HectorRDB, I should have been more specific. Yes, I am getting the same error:

```Error in Biobase::exprs(cds) : object 'cds' not found```

**Comment by HectorRDB** [comment]
Ok that is very weird. The last commit should have deleted the line `Biobase::exprs(cds)` and replace it with `Biobase::exprs(counts)`...
Can you tell me the output of 
```
is(donor1_fibroblast_cds)
getMethod("fitGAM","CellDataSet")
```

**Comment by BrianLohman** [comment]
Hi Hector,

I just restarted my R prior to gathering the output you requested and now it looks like fitGAM is running. I'm not sure what changed. It's still loading the latest devel version you pushed a few hours ago (1.3.01). It must have been hung up on something older in my environment.

The call to ```Biobase::``` is the the newest version: ```Biobase:exprs(counts)``` (below) so your last commit was good. 

The progress meter suggest it will be another 4-5 hours until it's done so I'll let you know what happens. 

Thanks again for your help,

Brian 


Just in case, here is the output  you requested:
```
> is(donor1_fibroblast_cds)
[1] "CellDataSet"      "ExpressionSet"    "eSet"             "VersionedBiobase" "Versioned"       
> getMethod("fitGAM","CellDataSet")
Method Definition:

function (counts, ...) 
{
    .local <- function (counts, U = NULL, genes = seq_len(nrow(counts)), 
        weights = NULL, offset = NULL, nknots = 6, verbose = TRUE, 
        parallel = FALSE, BPPARAM = BiocParallel::bpparam(), 
        control = mgcv::gam.control(), sce = TRUE, family = "nb") 
    {
        if (counts@dim_reduce_type != "DDRTree") {
            stop(paste0("For now tradeSeq only support Monocle with DDRTree", 
                "reduction. If you want to use another type", 
                "please use another format for tradeSeq inputs."))
        }
        y_to_cells <- counts@auxOrderingData[["DDRTree"]]
        y_to_cells <- y_to_cells$pr_graph_cell_proj_closest_vertex %>% 
            as.data.frame() %>% dplyr::mutate(cells = rownames(.)) %>% 
            dplyr::rename(Y = V1)
        root <- counts@auxOrderingData[[counts@dim_reduce_type]]$root_cell
        root <- y_to_cells$Y[y_to_cells$cells == root]
        mst <- monocle::minSpanningTree(counts)
        endpoints <- names(which(igraph::degree(mst) == 1))
        endpoints <- endpoints[endpoints != paste0("Y_", 
            root)]
        cellWeights <- lapply(endpoints, function(endpoint) {
            path <- igraph::shortest_paths(mst, root, endpoint)$vpath[[1]]
            path <- as.character(path)
            df <- y_to_cells %>% dplyr::filter(Y %in% path)
            df <- data.frame(weights = as.numeric(colnames(counts) %in% 
                df$cells))
            colnames(df) <- endpoint
            return(df)
        }) %>% bind_cols()
        pseudotime <- sapply(cellWeights, function(w) counts$Pseudotime)
        rownames(cellWeights) <- rownames(pseudotime) <- colnames(counts)
        gamOutput <- fitGAM(counts = Biobase::exprs(counts), 
            U = U, cellWeights = cellWeights, pseudotime = pseudotime, 
            genes = genes, weights = weights, offset = offset, 
            nknots = nknots, verbose = verbose, parallel = parallel, 
            BPPARAM = BPPARAM, control = control, sce = sce, 
            family = family)
        return(gamOutput)
    }
    .local(counts, ...)
}
<bytecode: 0x00000204dc2e7bd8>
<environment: namespace:tradeSeq>

Signatures:
        counts       
target  "CellDataSet"
defined "CellDataSet"
```

**Comment by HectorRDB** [comment]
Great.
Yes I've had similar experience when installing new versions of a package, they sometime do not load properly.
I will close this issue now. If another bug appear, you are more than welcome to open another one. 
Best
