### ISSUE TITLE
Choose number of knots for fitGam

### ISSUE THREAD

**Issue by nicodemus88** [statOmics/tradeSeq#57]
Hi, 
I'm trying tradeSeq on my single cell dataset consisting of 11,273 cells with 15,572 genes. The commands I used to run `evaluateK` is as follows

```
cd8SCE <- as.SingleCellExperiment(cd8)
counts <- as.matrix(assays(cd8SCE)$counts)
cd8_slingshot <- slingshot(Embeddings(cd8, "umap"), clusterLabels = cd8$seurat_clusters, start.clus = 4, extend = "n")
pseudotime <- slingPseudotime(cd8_slingshot, na = FALSE)
cellWeights <- slingCurveWeights(cd8_slingshot)
BPPARAM <- BiocParallel::bpparam()
BPPARAM$workers <- 20
icMat <- evaluateK(counts = counts, sds = cd8_slingshot, k = 3:12, nGenes = 200, verbose = TRUE)
```
The process finishes and I obtained the plot as well. However, I got some warnings as below and I was wondering if there's any problem with the analysis. 

```
Warning messages:
1: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS,  ... :
  Fitting terminated with step failure - check results carefully
2: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS,  ... :
  Fitting terminated with step failure - check results carefully
3: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS,  ... :
  Fitting terminated with step failure - check results carefully
4: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS,  ... :
  Fitting terminated with step failure - check results carefully
5: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS,  ... :
  Fitting terminated with step failure - check results carefully
```

Second, my graph looks a bit strange and I was wondering what number of knots I should use for `fitGam` function. 

![Picture1](https://user-images.githubusercontent.com/24598265/84468187-2b15d600-acb9-11ea-9d2e-7a8fc822ca6d.png)

Hoping to hear back soon. Thank you very much.

**Comment by HectorRDB** [comment]
Hi @nicodemus88,
Thanks for your interest in `tradeSeq`. 

For the first point, it means that fitting the model failed for 5 out of 500 genes. That is nothing to be worried about in general. A couple remarks though. First, this error should be captured in the latest version of `tradeSeq`. Could you try to re-install it from Github and see if the error still appears? Secondly, in my experience, 15 000 genes might be a little much, which would explain why it fails for some genes. 

The second point is a little weird though. In particular, the second and third plots should be identical up to the y-axis, which is clearly not the case here. Could you also try to install the latest version of `tradeSeq` from Github and see if the error still persists? 

Best

**Comment by nicodemus88** [comment]
Hi @HectorRD, thank you for your reply. 

I updated tradeSeq to version 1.2.01 and tried the steps above again. 
Now, I got this error. 

```
icMat <- evaluateK(counts = counts, sds = cd8_slingshot, k = 3:12, nGenes = 200, verbose = TRUE)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=05m 18s
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=05m 59s
  |++++++++++++++++++++++++++                        | 52% ~03m 17s      
Error in gam.fit4(x, y, sp, Eb, UrS = UrS, weights = weights, start = start, : inner loop 3; can't correct step size
```

How can I proceed after this since now the error stops the process from proceeding? 

My matrix is converted from a Seurat object after filtering and quality control. What other ways you suggest to filter out more genes? Should I use the matrix of only the variable genes (5000 genes)?

**Comment by HectorRDB** [comment]
Hi @nicodemus88,
The error is related to #53, it should be fixed on the github branch but not on the  main branch yet so please install `tradeSeq` using 
```
if(!requireNamespace("devtools", quietly = TRUE)) {
 install.packages("devtools") 
}
devtools::install_github("statOmics/tradeSeq")
```
This should fix the issue.

Using this latest version, you will also be able to find for which genes the model properly converged so the issue of the number of genes will be lessened. However, the computational aspect will remain, fitting on 5000 genes should take 1/3 of the time since `tradeSeq` is linear in the number of genes, but it would depend on your end goals.

**Comment by nicodemus88** [comment]
Hi @HectorRDB ,
Thanks for your reply. 
I tried the development version & I managed to complete the process without any errors. However, I still get a plot similar to the one earlier. So my question is, how many knots should I used for `fitGam`? FYI, I ran this on the original matrix (15,000 genes) without subsetting. 

![Picture1](https://user-images.githubusercontent.com/24598265/84490933-c66d7200-acde-11ea-8103-97b649220e71.png)

Thank you!

**Comment by HectorRDB** [comment]
Great that the devel version fixed it. I am still puzzled by the plot. Based on the third plot (which looks as expected), I would pick 6 knots (which is where there is an inflexion point). 
However, do you mind sharing a subset of your data that reproduces the plot above? I would like to investigate this issue.
Best

**Comment by nicodemus88** [comment]
Hi @HectorRDB, 
Thanks for your suggestion. I used 6 knots as well, but I encountered another error. I ran the command as a RScript as below:

```
BPPARAM <- BiocParallel::bpparam()
BPPARAM$workers <- 20
sce <- fitGAM(counts = counts, pseudotime = pseudotime, cellWeights = cellWeights, nknots = 7, verbose = FALSE, parallel = TRUE, BPPARAM = BPPARAM)
saveRDS(sce, file = "/lab/bt/single_cell/ANALYSIS/CD8/SCE_tradeseq.Rds")
```

The error message I got is:

```
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : write error, closing pipe to the master
Calls: fitGAM ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in gzfile(file, mode) : cannot open the connection
Calls: saveRDS -> gzfile
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '/lab/bt/single_cell/ANALYSIS/CD8/SCE_tradeseq.Rds', probable reason 'No such file or directory'
Execution halted
```

Do you know the reason for this error? Looks like an error parsing to `lapply` but I'm not sure what is the real issue here. 

Yes, sure. I don't mind sharing the dataset with you. I will email it to you with a WeTransfer link. Is that OK? 

Thank you very much.

**Comment by HectorRDB** [comment]
Thank you, I have received a file. I will take a look
Best

**Comment by HectorRDB** [comment]
Hi @nicodemus88 
Thanks for sharing the data. I took a look and found a little bug on the first plot, which should now be fixed. However, that does not explain the differences between the second and third figures.

After filtering to the top 8k genes (using `Seurat::findVariableFeatures`, I got this:
![image](https://user-images.githubusercontent.com/27447880/84868847-95de5d00-b07d-11ea-99f8-9c8e0f099dad.png)

This suggests using `nknots=6` which is consistent with what you did above.

For the second issue, I was not able to reproduce it. Bugs with `BiocParrallel` tend to be quite obscur and hard to troubleshoot. Previously, several other users managed to solve the bugs by decreasing the number of cores. I hope that works for you. 

Best

**Comment by ZHIDIHUAYUAN** [comment]
Hi,
I'm trying tradeSeq on my single cell dataset consisting of 3821 cells with 18962 genes. When I run the command `evaluateK`, I got the following result：
<img width="234" alt="image" src="https://user-images.githubusercontent.com/66869156/96403936-297e9080-120c-11eb-8d61-40c99c1eb395.png">
I don't know how to choose the number of knots. Should I only use the top 8k genes to run the command? In fact, I can't understand why I should do this, because the command `evaluateK` randomly picks genes. 
I also don't know how I can choose the top genes, because the data contains two conditions.

**Comment by HectorRDB** [comment]
Hi @ZHIDIHUAYUAN,
We recommend choosing the top genes for many reasons, including computational time and easier interpretation of results. In the case of the `evaluateK`, you want to run the function on the same set of genes as the one that you will use for the `fitGam` function so that the random sample of genes is fully representative. You want to estimate the value of `k` for the top genes, not for the one that will be filtered out.

With this in mind, we indeed recommend choosing only the top features in `tradeSeq`. The exact number would depend on the level of changes in your system but we have found that the top 10k genes are very often enough. To select those top 10k genes, you can use many filtering tools. We generally use either `Seurat::findVariableFeatures` or a filtering such as "at least x reads in y cells". 

Finally, we recommend you pay attention to the y-axis for both plots. The variations between the different values of `k`are small. Based on the plot alone, I would pick k=6 for example. 

Best

**Comment by ZHIDIHUAYUAN** [comment]
Thank you for your reply. 
I still have two questions:
(1) I understand that the `evaluateK `  and `fitGam ` function should be run on the same set of genes. In fact, my code is :
`part1<-subset(object.integrated, subset = seurat_clusters %in% c('0','2','12'))
part1_sce <- as.SingleCellExperiment(part1, assay="RNA")
part1_slingshot<-slingshot(part1_sce, clusterLabels = 'seurat_clusters', reducedDim = 'UMAP',start.clus='2')
icMat1 <- evaluateK(counts = as.matrix(assays(part1_slingshot)$counts),
                    pseudotime = slingPseudotime(part1_slingshot, na = FALSE),
                    cellWeights = slingCurveWeights(part1_slingshot),
                    conditions = factor(colData(part1_slingshot)$type),
                    nGenes = 500,
                    k = 3:10)
sce1 <- fitGAM(counts = as.matrix(assays(part1_slingshot)$counts),
               pseudotime = slingPseudotime(part1_slingshot, na = FALSE),
               cellWeights = slingCurveWeights(part1_slingshot),
               conditions = factor(colData(part1_slingshot)$type),
               nknots = 7,parallel = TRUE, BPPARAM = BPPARAM)`
I didn't filter out any gene. In the vignette, you mention that the AIC is expected to decrease as the number of knots gets higher. But, in my plot, it is not as expected. In this case, can I still choose k according to the plot?
(2) My data comes from two rats in different situations(OB & WT). The number of cells from OB is greater than the number of cells from WT. If I run `Seurat::findVariableFeatures` on the `part1[['RNA']]@counts` which contains cells from OB and WT, does the difference in cell number affect ?

**Comment by ZHIDIHUAYUAN** [comment]
Thank you for your reply.
I still have two questions:
(1) I understand that the evaluateK and fitGam function should be run on the same set of genes. In fact, my code is :
`part1<-subset(object.integrated, subset = seurat_clusters %in% c('0','2','12'))`
`part1_sce <- as.SingleCellExperiment(part1, assay="RNA")`
`part1_slingshot<-slingshot(part1_sce, clusterLabels = 'seurat_clusters', reducedDim = 'UMAP',start.clus='2')`
`icMat1 <- evaluateK(counts = as.matrix(assays(part1_slingshot)$counts), pseudotime = slingPseudotime(part1_slingshot, na = FALSE), cellWeights = slingCurveWeights(part1_slingshot), conditions = factor(colData(part1_slingshot)$type), nGenes = 500, k = 3:10)`
`sce1 <- fitGAM(counts = as.matrix(assays(part1_slingshot)$counts), pseudotime = slingPseudotime(part1_slingshot, na = FALSE), cellWeights = slingCurveWeights(part1_slingshot), conditions = factor(colData(part1_slingshot)$type), nknots = 6,parallel = TRUE, BPPARAM = BPPARAM)`
    I didn't filter out any gene. In the vignette, you mention that the AIC is expected to decrease as the number of knots gets higher. But, in my plot, it is not as expected. In this case, can I still choose k according to the plot?

(2) My data comes from two rats in different situations(OB & WT). The number of cells from OB is greater than the number of cells from WT. If I run Seurat::findVariableFeatures on the part1[['RNA']]@counts which contains cells from OB and WT, does the difference in cell number affect ?

**Comment by HectorRDB** [comment]
Hi, 
To answer your questions,
(1) The AIC will roughly decrease as k increases but in the plot, the y-axis variations are very small so it's not surprising that the trend is not really monotonous. I would anyway be careful in interpreting this plot without filtering.
(2) If the two conditions are very unbalanced, it might have an impact. In that case, you could do filtering for each condition and select the union for example. But in my experience, if the ratio is not too skewed (less than 3 to 1), it should not matter that much. 
As a side note, if you have two conditions, I would recommend looking at [the workshop we gave at Bioc2020](https://kstreet13.github.io/bioc2020trajectories/articles/workshopTrajectories.html) and at the latest tradeSeq version that can deal with conditions.

**Comment by ZHIDIHUAYUAN** [comment]
Thank you very much for your reply. This helps me a lot.

**Comment by lc822** [comment]
Hi,

My plots for the AIC values look very similar to @nicodemus88.  I am analysing a scRNA-seq dataset with ~25,000 cells and I have filtered for the top 3000 variable genes identified by Seurat.

```
set.seed(5)
icMat <- evaluateK(counts = counts, sds = sds, k = 3:10, nGenes = 200, verbose = TRUE)
```
counts is a matrix of raw counts, sds is my SlingshotDataSet object

![000003](https://user-images.githubusercontent.com/22564745/97420923-cecbef80-1903-11eb-8f53-785587707fc0.png)

What would you suggest to do in this case?  I would be happy to share the data if this helps.

Slingshot identified three lineages, of which I am only interested in two.  I wondered if I could filter to retain only these lineages for running tradeSeq.  I tried as follows however I received an error.

```
set.seed(5)
icMat <- evaluateK(counts = counts, pseudotime = slingPseudotime(sds)[, c(1, 3)], 
                   cellWeights = slingCurveWeights(sds)[, c(1, 3)], 
                   k = 3:10, nGenes = 200, verbose = TRUE)
```

> Error in .assignCells(cellWeights) : 
>   Some cells have no positive cell weights.

I assume this is because some cells are only assigned to the lineage that I have removed?

Best wishes,
Lucy

`sessionInfo()`

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] SingleCellExperiment_1.10.1 SummarizedExperiment_1.18.2 DelayedArray_0.14.1        
 [4] matrixStats_0.56.0          Biobase_2.48.0              GenomicRanges_1.40.0       
 [7] GenomeInfoDb_1.24.2         IRanges_2.22.2              S4Vectors_0.26.1           
[10] BiocGenerics_0.34.0         slingshot_1.6.0             princurve_2.1.4            
[13] Seurat_3.1.5                tradeSeq_1.3.19            

loaded via a namespace (and not attached):
  [1] Rtsne_0.15             VGAM_1.1-3             colorspace_1.4-1       ellipsis_0.3.1        
  [5] ggridges_0.5.2         XVector_0.28.0         rstudioapi_0.11        leiden_0.3.3          
  [9] listenv_0.8.0          ggrepel_0.8.2          codetools_0.2-16       splines_4.0.3         
 [13] docopt_0.6.1           knitr_1.28             jsonlite_1.7.1         packrat_0.5.0         
 [17] ica_1.0-2              cluster_2.1.0          png_0.1-7              uwot_0.1.8            
 [21] pheatmap_1.0.12        sctransform_0.2.1      compiler_4.0.3         httr_1.4.2            
 [25] lazyeval_0.2.2         Matrix_1.2-18          limma_3.44.3           htmltools_0.5.0       
 [29] tools_4.0.3            rsvd_1.0.3             igraph_1.2.5           gtable_0.3.0          
 [33] glue_1.4.1             GenomeInfoDbData_1.2.3 RANN_2.6.1             reshape2_1.4.4        
 [37] dplyr_1.0.0            Rcpp_1.0.4.6           slam_0.1-47            DDRTree_0.1.5         
 [41] vctrs_0.3.1            ape_5.4-1              nlme_3.1-149           lmtest_0.9-38         
 [45] xfun_0.14              stringr_1.4.0          globals_0.12.5         lifecycle_0.2.0       
 [49] irlba_2.3.3            renv_0.10.0-46         future_1.17.0          edgeR_3.30.3          
 [53] zlibbioc_1.34.0        MASS_7.3-53            zoo_1.8-8              scales_1.1.1          
 [57] monocle_2.16.0         RColorBrewer_1.1-2     yaml_2.2.1             reticulate_1.16       
 [61] pbapply_1.4-2          gridExtra_2.3          ggplot2_3.3.1          fastICA_1.2-2         
 [65] stringi_1.4.6          densityClust_0.3       BiocParallel_1.22.0    rlang_0.4.8           
 [69] pkgconfig_2.0.3        bitops_1.0-6           qlcMatrix_0.9.7        lattice_0.20-41       
 [73] ROCR_1.0-11            purrr_0.3.4            patchwork_1.0.0        htmlwidgets_1.5.1     
 [77] cowplot_1.0.0          tidyselect_1.1.0       RcppAnnoy_0.0.16       plyr_1.8.6            
 [81] magrittr_1.5           R6_2.4.1               generics_0.0.2         combinat_0.0-8        
 [85] pillar_1.4.4           mgcv_1.8-33            fitdistrplus_1.1-1     survival_3.2-7        
 [89] RCurl_1.98-1.2         tsne_0.1-3             tibble_3.0.1           future.apply_1.5.0    
 [93] crayon_1.3.4           KernSmooth_2.23-17     plotly_4.9.2.1         viridis_0.5.1         
 [97] locfit_1.5-9.4         grid_4.0.3             data.table_1.13.2      FNN_1.1.3             
[101] HSMMSingleCell_1.8.0   sparsesvd_0.2          digest_0.6.25          tidyr_1.1.0           
[105] munsell_0.5.0          viridisLite_0.3.0   
```

**Comment by lc822** [comment]
This is what it looked like when I ran it again with a different seed.

```
set.seed(10)
icMat <- evaluateK(counts = counts, sds = sds, k = 3:10, nGenes = 200, verbose = TRUE)
```

![evaluateK_all_seed10](https://user-images.githubusercontent.com/22564745/97429293-21f76f80-190f-11eb-99b3-99cccf9e35b4.png)
